version: "3.9"

services:
  nextcloud:
    image: nextcloud:30
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8082:80
    volumes:
      - ./nextcloud_data:/var/www/html
      - ./nextcloud_storage:/var/www/html/data
    depends_on:
      - db
      - redis

  db:
    image: mariadb:10.6
    container_name: nextcloud_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}             
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: unless-stopped

volumes:
  db_data:
