version: "3.8"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "8083:80"
    volumes:
      - ./data:/data
    environment:
      - DOMAIN=http://vault.local.lan       
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false                # disable after first user created
      - ADMIN_TOKEN=${ADMIN_TOKEN}           
      - LOG_LEVEL=info
      - TZ=Europe/London
